server:
  port: 7903
spring:
  application:
    name: client
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
provider:
  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000