server:
  port: 7950
spring:
  application:
    name: config-server-eureka
  cloud:
    config:
      server:
        git:
          uri: http://git.oschina.net/IMZLF/spring-config      # 配置Git仓库的地址
          username:                                                         # Git仓库的账号
          password:                                                         # Git仓库的密码
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/