server:
  port: 7901
user:
  userServicePath: http://localhost:7900/user/
spring:
  application:
    name: client
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/